### ISSUE TITLE
[Impersonation] Add User Impersonation UI option for Admins

### ISSUE THREAD

**Issue by 0xnmn** [coding-blocks/gondor#46] opened 2020-05-16 11:23 UTC
Impersonation is helpful feature for debugging in both dev and prod environments. The current implementation is such that, if the logged in user is an Admin, you can add a cookie named [iuid](https://github.com/coding-blocks/gondor/blob/master/api/middlewares/authenticate.js#L14) with the value of `user_id` of any user, on refresh you will be logged in as that user. Removing the cookie will take you back to your own account.

The idea is to create a UI option for to impersonate any user.
1) Create a modal which shows a [user select field](https://github.com/coding-blocks/gondor/blob/master/app/components/UserSelect/index.js), on submit it adds the cookie and reloads the page.

2) Add a dropdown item above logout button in the navbar named Impersonate, clicking on which the modal should open.
<img width="216" alt="Screenshot 2020-05-16 at 4 50 05 PM" src="https://user-images.githubusercontent.com/22571395/82118484-6514ba80-9795-11ea-9a53-b758f267b8e8.png">

**Comment by jugshaurya** [comment] 2020-05-16 12:53
@hereisnaman may I do this?
assign it to me.

**Comment by 0xnmn** [comment] 2020-05-16 13:07
@jugshaurya you can start working on it.

**Comment by jugshaurya** [comment] 2020-05-16 14:28
@hereisnaman 
progress Report and some help wanted:

- Point2 is done 😍.
- Point1 requires all the users to show in the select user dropdown. Can you tell me how can't get all the users when I have created a single sign-on #CodingBlocks. No local Auth is set up in my case.
- Just some Pointers Please.
![point2](https://user-images.githubusercontent.com/39825643/82122167-90a49e80-97af-11ea-9166-3241c1cec223.gif)

**Comment by 0xnmn** [comment] 2020-05-16 15:14
> @hereisnaman
> progress Report and some help wanted:
> 
>     * Point2 is done 😍.
> 
>     * Point1 requires all the users to show in the select user dropdown. Can you tell me how can't get all the users when I have created a single sign-on #CodingBlocks. No local Auth is set up in my case.
> 
>     * Just some Pointers Please.
>       ![point2](https://user-images.githubusercontent.com/39825643/82122167-90a49e80-97af-11ea-9166-3241c1cec223.gif)

Good progress. I have added a script [here](https://github.com/coding-blocks/gondor/blob/master/api/bin/seedUsers.js) to seed users in the database. You can use that. 

`npx babel-node api/bin/seedUsers.js`

**Comment by jugshaurya** [comment] 2020-05-16 17:44
@hereisnaman, So basically you want to show all the available user in impersonating select dropdown and then select the user to add that user based cookie and reload the page right? I am new to graphql can you tell me how can I get all the Database saved users ?

**Comment by jugshaurya** [comment] 2020-05-16 18:02
@hereisnaman 

![invite_users](https://user-images.githubusercontent.com/39825643/82126872-2a2e7900-97cd-11ea-93d9-f38eaa2be81d.png)

Point 1 functionality to show the user is similar to the Invite Users as well as Select Zoom Account.I guess all three places require the same thing to get respective data and set them as select options. Right?

**Comment by jugshaurya** [comment] 2020-05-16 18:11
@hereisnaman, So basically you want to show all the available user in impersonating select dropdown and then select the user to add that user based cookie and reload the page right? I am new to graphql can you tell me how can I get all the Database saved users ?

**Comment by 0xnmn** [comment] 2020-05-16 19:06
> @hereisnaman, So basically you want to show all the available user in impersonating select dropdown and then select the user to add that user based cookie and reload the page right? I am new to graphql can you tell me how can I get all the Database saved users ?

Yes all those places are using the same component. You don't need to perform any queries. You can simply use [this](https://github.com/coding-blocks/gondor/blob/master/app/components/UserSelect/index.js) component and it will handle it for you.

**Comment by jugshaurya** [comment] 2020-05-17 16:05
@hereisnaman, should I create the new modal inside app/modals and create a new folder named Impersonate and a index.js file to maintain the code consistency and implement the same component as AddEvent to solve this issue? If not can you tell me how the props to UserSelect Component mainly the {value,  availabilityStatusDuring,  onChange} are going to be ? or from where are they coming from. I am unable to figure that out.

**Comment by 0xnmn** [comment] 2020-05-17 17:11
> @hereisnaman, should I create the new modal inside app/modals and create a new folder named Impersonate and a index.js file to maintain the code consistency and implement the same component as AddEvent to solve this issue? If not can you tell me how the props to UserSelect Component mainly the {value, availabilityStatusDuring, onChange} are going to be ? or from where are they coming from. I am unable to figure that out.

Yes create a new modal names Impersonate. You need to study the Components/Event/Form to see how to use UserSelect. You do not need to pass any availabilityStatus prop and we don't have to show it.

**Comment by jugshaurya** [comment] 2020-05-19 16:34
@hereisnaman I got that I need to useUserSelect to select the users once I got them. But the problem is in listing/getting in the users into the impersonate dropdown. For that I have to query the graphqlApi to get all the users. whose code is in UserSelect. But I am Stuck in here. Can you give me a hint?

I may be wrong but I am passing all the roles to get the users. But No luck so far.
 
![s](https://user-images.githubusercontent.com/39825643/82353074-8dfab100-9a1c-11ea-9373-16d95c7056d1.png)

**Comment by 0xnmn** [comment] 2020-05-19 16:54
@jugshaurya you don't need to pass any variables, Also it should not be a multi select only only single user select.

I wonder why you are creating a separate component just for the form. You can simply put that in the modal. rename users => user and setUsers -> setUser.

**Comment by jugshaurya** [comment] 2020-05-19 18:47
@hereisnaman, 

**Progress:** got the users into the dropdown, like this. 
**Remains**. setting the cookie named `iuid`, for that, I think I have to write down a Base Controller and decorator to set cookie `iuid` to `user_id` just like you did with logout. right?

![a](https://user-images.githubusercontent.com/39825643/82365936-02d6e680-9a2f-11ea-9221-d172a71a2804.gif)

**Comment by 0xnmn** [comment] 2020-05-19 19:30
> @hereisnaman,
> 
> **Progress:** got the users into the dropdown, like this.
> **Remains**. setting the cookie named `iuid`, for that, I think I have to write down a Base Controller and decorator to set cookie `iuid` to `user_id` just like you did with logout. right?
> 

Set cookie from client side only and reload the page.

**Comment by 0xnmn** [comment] 2020-05-20 21:11
@jugshaurya The cookie path set for iuid is not correct because of which it is not working. Please do proper testing before raising the PR. The path should be set to root.

Fix this to claim the bounty. Also update the label of input field to User and fix the css issue.
<img width="531" alt="Screenshot 2020-05-21 at 2 40 48 AM" src="https://user-images.githubusercontent.com/22571395/82497803-86b2d080-9b0c-11ea-97eb-2fea5c115be2.png">

**Closed as completed** 2020-05-21 16:16 UTC
Labels: BOSS, BOUNTY: 500
